bot:
  name: "attendance_itmo_bot"
  token: ${BOT_TOKEN}

jms:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  service-endpoint: "https://message-queue.api.cloud.yandex.net/b1gd8ivetmb3vka656qj/dj6000000018nifk04sq/ymq-01"
  signing-region: "ru-central1"
  queue-names:
    attendance-send-queue: "ymq-01"
