server:
  port: 8082

jms:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  queues:
    otv-node:
      name: "ymq-01"
      service-endpoint: "https://message-queue.api.cloud.yandex.net/b1gd8ivetmb3vka656qj/dj6000000018nifk04sq/ymq-01"
      signing-region: "ru-central1"
    otv-dispatcher:
      name: "ymq-02"
      service-endpoint: "https://message-queue.api.cloud.yandex.net/b1gd8ivetmb3vka656qj/dj6000000018pg2k04sq/ymq-02"
      signing-region: "ru-central1"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otv
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true